import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Button from "@/components/Button";
import Name from "@/components/Name";
import Portfolio from "@/components/Portfolio";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Darya Bazilevskaya Portfolio Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          {/* <div className={styles.neonText}>Darya</div> */}
          <Name />
          <div className={styles.menu}>
            <Link className={styles.a} href="/menu/about">
              About me
            </Link>
            <Link className={styles.a} href="/menu/skills">
              My Skils
            </Link>
            <Link className={styles.a} href="/menu/portfolioPage">
              Portfolio
            </Link>
            <Link className={styles.a} href="/menu/contact">
              Contact me
            </Link>
          </div>
        </div>
        <div className={styles.sec2}>
          <div>
            <Image
              className={styles.image}
              // className={styles.logo}
              src="/IMG_6018.jpg"
              alt="Darya Bazilevskaya"
              width={240}
              height={240}
              style={{
                objectFit: "cover",
                borderRadius: "50px",
              }}
              priority
            />
          </div>
          <div className={styles.intro}>
            <h3>
              Hello. My name is Darya and I am a web developer. I have been
              involved in industry for some years now. I use MERN Stack for my
              projects. My skills include JavaScript, TypeScript, React, HTML,
              CSS, Agile development and Git.
            </h3>
            {/* <button>Contsct me</button> */}
          </div>
        </div>
        <Button />
        <Portfolio />
        {/* <Laptop /> */}
      </main>
    </>
  );
}
