import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Button from "@/components/Button";
import Name from "@/components/Name";
import Modal from "@/components/Modal";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [openModal, setOpenModal] = useState(false);
  const [text, setText] = useState("");
  return (
    <>
      <Head>
        <title>Darya Bazilevskaya Portfolio Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          {/* <div className={styles.neonText}>Darya</div> */}
          <Name />
          <div className={styles.menu}>
            <Link className={styles.a} href="/menu/about">
              About me
            </Link>
            <Link className={styles.a} href="/menu/skills">
              My Skils
            </Link>
            <Link className={styles.a} href="/menu/portfolio">
              Portfolio
            </Link>
            <Link className={styles.a} href="/menu/contact">
              Contact me
            </Link>
          </div>
        </div>
        <div className={styles.sec2}>
          <div>
            <Image
              className={styles.image}
              // className={styles.logo}
              src="/IMG_3433.jpg"
              alt="Darya Bazilevskaya"
              width={180}
              height={180}
              style={{
                objectFit: "cover",
                borderRadius: "50px",
              }}
              priority
            />
          </div>
          <div className={styles.intro}>
            <h1>Hello. My name is Darya and I am a web developer.</h1>
            {/* <button>Contsct me</button> */}
          </div>
        </div>
        <Button />
        <div className={styles.sec3}>
          <p className={styles.port}>Portfolio</p>
        </div>

        <div className={styles.project}>
          <Image
            // className={styles.logo}
            src="/store-project.png"
            alt="store-project"
            width={900}
            height={700}
            style={{
              objectFit: "cover",
              borderRadius: "50px",
            }}
            priority
          />
          <div className={styles.projectButtons}>
            <button
              className={styles.button91}
              onClick={() => setOpenModal(true)}
            >
              About
            </button>
            <Modal
              open={openModal}
              text="The 3D Model store was our second unit project at GA. It uses react without backend."
              onClose={() => setOpenModal(false)}
            />

            <a href="https://store-3d-model-app.herokuapp.com/store/">
              <button className={styles.button91}>Visit Site</button>
            </a>
          </div>
        </div>

        <div className={styles.project}>
          <Image
            // className={styles.logo}
            src="/battleship-project.png"
            alt="battleship-project"
            width={800}
            height={600}
            style={{
              objectFit: "cover",
              borderRadius: "50px",
            }}
            priority
          />

          <div className={styles.projectButtons}>
            <button
              className={styles.button91}
              onClick={() => setOpenModal(true)}
            >
              About
            </button>
            <Modal
              open={openModal}
              text="This project was final project of our first unit at GA. The project is done in vanila JS and and I a very proud of it. It is classic battleship game but its done without separation of players for technical limitations of JS. Even though it is fully functional andis following the main concept of the game"
              onClose={() => setOpenModal(false)}
            />

            <a href="https://bazilevsd.github.io/battleship-game/">
              <button className={styles.button91}>Visit Site</button>
            </a>
          </div>
        </div>

        {/* <Laptop /> */}
      </main>
    </>
  );
}
